apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-test-deployment
  namespace: default
spec:
  replicas: 10
  revisionHistoryLimit: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 7
  selector:
    matchLabels:
      service: nodejs-test-service
  template:
    metadata:
      labels:
        app: nodejs-test
        service: nodejs-test-service #labels for the pods e.g kubectl get pod -l "service in (http-server)"
        version: 1.0.0
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: nodejs-test
        image: nodejs-test:latest #private Docker registry
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
